### ISSUE TITLE
building problem [vite:legacy-post-process] missing field `ctxt`

### ISSUE THREAD

**Issue by LSDNaHCO3** [CyanSalt/vite-plugin-legacy-swc#13]
[vite:legacy-post-process] missing field `ctxt`

**Comment by Zeta611** [comment]
I moved back to using [`@vitejs/plugin-legacy`](https://www.npmjs.com/package/@vitejs/plugin-legacy), which solves this issue.

**Comment by CyanSalt** [comment]
Thanks for the feedback. This issue appeared in `@swc/core@>=1.7`.

I'm not sure what happened to the upstream package, but I added a test for the build process and fixed this issue based on the test.

[`1.2.1`](https://github.com/CyanSalt/vite-plugin-legacy-swc/releases/tag/v1.2.1) with this fix has been released, you can try it.

**Comment by CyanSalt** [comment]
This issue is expected to be fixed, so I'm closing it.
