### ISSUE TITLE
 Packaging will generate two sets of codes

### ISSUE THREAD

**Issue by vijay19920608** [CyanSalt/vite-plugin-legacy-swc#6]
Packaging will generate two sets of codes, one is for modern browsers, and the other is code that is compatible with lower versions. How to set up to generate only one set of code that is compatible with lower versions?

**Comment by CyanSalt** [comment]
What you want is probably [`renderModernChunks`](https://github.com/CyanSalt/vite-plugin-legacy-swc?tab=readme-ov-file#rendermodernchunks). I have not tried this feature, feel free to provide feedback if you have any questions.
